### ISSUE TITLE
Should we archive this repository?

### ISSUE THREAD

**Issue by samccann** [ansible-community/ansible-buenosaires-meetup#1]
We are reconsidering how meetups share slides etc. There was a question raised on why we are separating these by geo vs jsut having one location where meetup organizers can share slides and perhaps reuse parts of other meetup presentations etc.

What are your thoughts on that? Do you want to keep this repository open for future meetups? Are you looking mostly for a place to upload presentations? etc.

**Comment by leogallego** [comment]
Hi @samccann, the idea originally was to host presentations and possible code examples used in workshops here. 
One of the reasons I think "geo" repos are useful is language. 
Most local meetups use their own language for their presentations.

I'm thinking if this could be moved to the forum, but, if we work with the organisers to improve collaboration, having a repo with versioned files (and possibly localized) might prove useful vs just uploading the slides to the past event in the forum topic. 

I would keep this one. I need to take the time to search and upload the presentations.

**Comment by samccann** [comment]
here's the forum discussion - https://forum.ansible.com/t/replacing-the-individual-meetup-github-repos/5741  and very valid points about languages

**Comment by samccann** [comment]
The other thing I worry about - this repo hasn't been used in the year it's been around. Do you anticipate someone will start using this repo soon?

**Comment by samccann** [comment]
Ok ends up most people who use the github repos for meetups want to keep it. So I'll close this issue, but if this repo here ends up staying empty, it might get archived the next time we do a tidy up :-)
